### ISSUE TITLE
Installation Trouble via Pip

### ISSUE THREAD

**Issue by madarax64** [yudivian/fuzzython#2]
Hello,
I tried to install the library using the command <code>pip install fuzzython </code>,  but I'm receiving the following error:

<code>
Collecting Fuzzython
  Using cached Fuzzython-0.1.0.tar.gz

    Complete output from command python setup.py egg_info: 

    Traceback (most recent call last): 

      File "<string>", line 1, in <module> 

      File "C:\Users\Mubarak\AppData\Local\Temp\pip-build-wkwofsm9\Fuzzython\setup.py", line 13, in <module>

        long_description=open('README.md').read(), 

    FileNotFoundError: [Errno 2] No such file or directory: 'README.md' 
</code>

I'm running Python 3.6.2 on PC running Windows 10 x64. The Python version is also 64-bit.

Could you help please?
Thanks

**Comment by redcyb** [comment]
@madarax64 
pip install https://github.com/yudivian/fuzzython.git

**Comment by madarax64** [comment]
@redcyb Received the following error:

![error](https://user-images.githubusercontent.com/4976654/47793820-d44bca80-dd27-11e8-8075-c0892327ec30.PNG)

**Comment by 0xrushi** [comment]
yes, i'm also getting this please help

**Comment by 0xrushi** [comment]
found it this works ,  :smiley:  :smiley:
pip install git+https://github.com/yudivian/fuzzython.git

**Comment by necmialtuk** [comment]
i have also same problem. How can i fix it? Please help!
